spring.profiles.active: prod

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/bookmark
    username: bookmark
    password: bookmark
  application:
    name: bookmark
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    jdbc: off
    jdbc.sqltiming: debug

server:
  port: 8082
eureka:
  client:
    eureka-server-port: http://localhost:8761/
